### PR TITLE
Added a cool bio with similar suggestions commented.

### PR DESCRIPTION
**Pull request by fauxriarty**
The bios suggested go with the rest of the portfolio's content :)

### CODE REVIEW

**Comment by TolulopeJoel** [comment]
Thanks so much @fauxriarty . I appreciate you.

**Comment by TolulopeJoel** [comment]
Thanks so much @fauxriarty . I appreciate you.

**Comment by fauxriarty** [comment]
You're welcome!

**Comment by fauxriarty** [comment]
Could you add the label for hacktoberfest accepted?

**Comment by TolulopeJoel** [comment]
> Could you add the label for hacktoberfest accepted?

Done

**Pull request merged**
